### ISSUE TITLE
请问axum中要做orm缓存应该如何实现？

### ISSUE THREAD

**Issue by lidh15** [axumrs/axum-rs-archived#3]
类似这种 https://github.com/Suor/django-cacheops 对频繁查询的对象从数据库挪到redis做缓存的。

**Comment by axumrs** [comment]
sea orm 只不过是一个隐藏了SQL语句的工具，其所谓的缓存和原生SQL或者其它语言是一样：利用 redis 等中间件缓存查询结果。具体为：在获取数据时，先从redis中查找是否有对应的缓存，如果有则直接把redis的结果返回；如果没有，则从数据库中查询，并将结果返回，同时把结果存储到 redis 中。
有关 redis 的教程请查阅：https://axum.rs/topic/roaming-axum/redis
如果你需要我写好代码给你参考，请转账300美金，再与我TG私聊。（不需要喷我，我已经把思路和参考教程都发给你了，我说的是如果你需要我写好代码给你参考）
另外，本仓库并未涉及 sea orm，只是我们的教程中有这方面的课程，请不要在本仓库提出无关的问题。建议你在相关课程的仓库提出，或者通过TG群提问，或者通过付费方式与站长私聊。
